# Generated by Django 4.2.11 on 2024-05-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
